### ISSUE TITLE
 C++ has a a latex shortcut that needs to be added to the automatic conversion

### ISSUE THREAD

**Issue by kilon** [pillar-markup/pillar-mode#1]
C++ has a a latex shortcut that needs to be added to the automatic conversion

**Comment by DamienCassou** [comment]
Are you talking about `\ind{C++}`?

**Comment by kilon** [comment]
yes also add Java to the list.

for example 

"\ind{Java} or \ind{C++}"

**Comment by DamienCassou** [comment]
Fixed in 4f74f324351bc4da00c0c8da5d32514db07ef362
