### ISSUE TITLE
\ind{block} for identifying "block" 

### ISSUE THREAD

**Issue by kilon** [pillar-markup/pillar-mode#7]
an example can be found in page 73 of PBE section "When to use [ ] or ( )" first paragraph , line 4.

**Comment by DamienCassou** [comment]
I don't see any problem with the latest version of the converter. `\ind{block}` should just be converted to `block` as the `\ind` LaTeX command is here to add its parameter to the index and display it as is. The definition of the command is:

``` latex
\newcommand{\ind}[1]{\index{#1}#1\xspace} % plain text
```

I'm closing this entry for now. Feel free to reopen.
